### PR TITLE
Allowing configuration of separate endpoints for CAS login and logout

### PR DESCRIPTION
**Pull request by chapmajs**
This PR allows configuration of the plugin to use different service paths for CAS login and logout success. Currently, a single endpoint is allowed, which requires checking to see if a token is present in the params to guess whether we're coming back from a login or a logout.

If separate paths aren't configured, the plugin uses a single service URL.

### CODE REVIEW

**Comment by davidmc24** [comment]
I need more context around the scenario you're encountering to know how best to support it.  I don't think this is the right way, as it's imposing additional (albeit optional) top-level config for what I currently think is a very edge use-case.

Also, note that CAS `/logout` endpoint returning you to the service URL is not a mandatory part of the protocol; rather it's a "might".

**Comment by chapmajs** [comment]
We'd like to have separate endpoints for successful login and logout, rather than having to check to see if  there's a ticket in the params and *assuming* it's a logout if there isn't a ticket.

**Comment by davidmc24** [comment]
If you're interested in this sort of functionality, I think it would be better to consider additions to the api of `ShiroCasUtils.logout` and/or `ShiroCasUrlBuilder.forLogout` rather than new configuration settings.

**Comment by chapmajs** [comment]
You're suggesting something like `ShiroCasUrlBuilder.forLogout("/your/logout/success/path/here")` instead of putting it in the configuration?

**Comment by davidmc24** [comment]
The shiro-cas plugin doesn't currently control anything about the logout process.  It merely provides ways for the application to easily use its understanding of the location of the CAS server and how to assemble logout URLs.  What I'm hearing from you is that you want the ability to customize the assembly of the service URL in this case.  I'm still not seeing a compelling reason for this feature at all, however.

**Comment by davidmc24** [comment]
Meaning, I don't think that logout should need separate handling from any other case where you end up on the callback URL without a token.

**Comment by chapmajs** [comment]
Yeah, looks like we were making some incorrect assumptions based on the way one particular CAS server works! Closing the PR.

**Pull request closed without merging**
